In [6]:
def solucionLineal(a, b):
    if a == 0:
        print("No se puede resolver el sistema: ax + b = 0")
        return 0
    return -b / a

a, b = 3, 2
x = solucionLineal(a, b)

print(f"La solución del sistema {a}x + {b} = 0")
print(f"Es x = {x:.2f}")

La solución del sistema 3x + 2 = 0
Es x = -0.67


In [5]:
a, b = 0, 2
x = solucionLineal(a, b)

print(f"La solución del sistema {a}x + {b} = 0")
print(f"Es x = {x:.2f}")

No se puede resolver el sistema: ax + b = 0
La solución del sistema 0x + 2 = 0
Es x = 0.00


In [2]:
capitales = ['#Ciudad Victo*ria', 'cuerna#vaca', 'Morelia!', 'xalapa', 'Tepic', 'hermos*illo',
 'toluca?', 'San? Luis Potosí', '*Mexicali', 'Villahermosa', 'Tuxtla Gutiérrez#',
 'Colima', 'la Paz#', 'Guadalajara', 'C*ampeche!', 'Durango', 'Zacatecas',
 '!Chetumal', 'Ciudad# de México', 'chilpancingo*', 'Chihua#hua', '?Aguascalientes',
 'Oaxaca de Juárez*', '?Puebla', 'Quer?étaro', 'Mérida', 'guanajuato',
 'pachu*ca', '#Saltillo#', 'Culiacán!', 'Tlaxcala', 'monterrey']

In [1]:
import re

def limpiar(textos):
    limpios = []
    for texto in textos:
        texto = texto.strip()
        texto = re.sub("[!#?*]", "", texto)
        texto = texto.title()
        limpios.append(texto)
    return limpios

In [3]:
limpiar(capitales)

['Ciudad Victoria',
 'Cuernavaca',
 'Morelia',
 'Xalapa',
 'Tepic',
 'Hermosillo',
 'Toluca',
 'San Luis Potosí',
 'Mexicali',
 'Villahermosa',
 'Tuxtla Gutiérrez',
 'Colima',
 'La Paz',
 'Guadalajara',
 'Campeche',
 'Durango',
 'Zacatecas',
 'Chetumal',
 'Ciudad De México',
 'Chilpancingo',
 'Chihuahua',
 'Aguascalientes',
 'Oaxaca De Juárez',
 'Puebla',
 'Querétaro',
 'Mérida',
 'Guanajuato',
 'Pachuca',
 'Saltillo',
 'Culiacán',
 'Tlaxcala',
 'Monterrey']

In [6]:
import numpy

u = numpy.arange(3) + 1
v = numpy.arange(3) + 4

u, v

(array([1, 2, 3]), array([4, 5, 6]))

In [7]:
numpy.dot(u, v)

np.int64(32)

In [8]:
numpy.linalg.norm(u), numpy.linalg.norm(v)

(np.float64(3.7416573867739413), np.float64(8.774964387392123))

In [9]:
u / numpy.linalg.norm(u)

array([0.26726124, 0.53452248, 0.80178373])

In [10]:
v / numpy.linalg.norm(v)

array([0.45584231, 0.56980288, 0.68376346])

In [12]:
(v - u).dot((v - u)) ** 0.5

np.float64(5.196152422706632)

In [14]:
numpy.linalg.norm(v - u)

np.float64(5.196152422706632)

In [15]:
u = numpy.array([3, 4])
v = numpy.array([-4, 3])

nu = u.dot(u) ** 0.5
nv = v.dot(v) ** 0.5

nu, nv

(np.float64(5.0), np.float64(5.0))

In [17]:
a = numpy.acos(u.dot(v) / (nu * nv))

a

np.float64(1.5707963267948966)

In [ ]:
a * 180 / numpy.pi

np.float64(90.0)

In [19]:
numpy.degrees(a)

np.float64(90.0)

In [20]:
u.dot(v)

np.int64(0)